### ISSUE TITLE
external-host-error doesn't have useful reason for failure

### ISSUE THREAD

**Issue by eflopez** [mend/renovate-on-prem#266]
Hello! 

We've got a large number of Ruby repositories that abort with `external-host-error` - these were failing for several weeks. This seems to be intermittent, sometimes it works.

However, there is only a stack trace. There doesn't seem to be any useful information to try and investigate a root cause. Here is the log.

```json
{
  "name": "renovate",
  "hostname": "ip-10-37-5-195.delivery.realestate.com.au",
  "pid": 28,
  "level": 20,
  "logContext": "IlfTuHCPI",
  "repository": "renovate-test/ruby-three",
  "msg": "getRubygemsOrgDependency(json)",
  "time": "2023-04-04T10:30:11.663Z",
  "v": 0
}
{
  "name": "renovate",
  "hostname": "ip-10-37-5-195.delivery.realestate.com.au",
  "pid": 28,
  "level": 20,
  "logContext": "IlfTuHCPI",
  "repository": "renovate-test/ruby-three",
  "err": {
    "name": "AggregateError",
    "message": "\n Error: external-host-error\n at VersionsDatasource.updateRubyGemsVersions (/usr/src/app/node_modules/renovate/dist/modules/datasource/rubygems/versions-datasource.js:88:23)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "stack": "AggregateError: \n Error: external-host-error\n at VersionsDatasource.updateRubyGemsVersions (/usr/src/app/node_modules/renovate/dist/modules/datasource/rubygems/versions-datasource.js:88:23)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at next (/usr/src/app/node_modules/p-map/index.js:43:14)\n at /usr/src/app/node_modules/p-map/index.js:67:7"
  },
  "msg": "Aggregate error is thrown",
  "time": "2023-04-04T10:30:11.664Z",
  "v": 0
}
{
  "name": "renovate",
  "hostname": "ip-10-37-5-195.delivery.realestate.com.au",
  "pid": 28,
  "level": 20,
  "logContext": "IlfTuHCPI",
  "repository": "renovate-test/ruby-three",
  "err": {
    "name": "AggregateError",
    "message": "\n Error: external-host-error\n at VersionsDatasource.updateRubyGemsVersions (/usr/src/app/node_modules/renovate/dist/modules/datasource/rubygems/versions-datasource.js:88:23)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "stack": "AggregateError: \n Error: external-host-error\n at VersionsDatasource.updateRubyGemsVersions (/usr/src/app/node_modules/renovate/dist/modules/datasource/rubygems/versions-datasource.js:88:23)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at next (/usr/src/app/node_modules/p-map/index.js:43:14)\n at /usr/src/app/node_modules/p-map/index.js:67:7"
  },
  "msg": "Aggregate error is thrown",
  "time": "2023-04-04T10:30:11.664Z",
  "v": 0
}
{
  "name": "renovate",
  "hostname": "ip-10-37-5-195.delivery.realestate.com.au",
  "pid": 28,
  "level": 40,
  "logContext": "IlfTuHCPI",
  "repository": "renovate-test/ruby-three",
  "hostType": "rubygems",
  "packageName": "json",
  "err": {
    "message": "Rubygems fetch error",
    "stack": "Error: Rubygems fetch error\n at VersionsDatasource.updateRubyGemsVersions (/usr/src/app/node_modules/renovate/dist/modules/datasource/rubygems/versions-datasource.js:88:67)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
  },
  "msg": "Host error",
  "time": "2023-04-04T10:30:11.664Z",
  "v": 0
}
{
  "name": "renovate",
  "hostname": "ip-10-37-5-195.delivery.realestate.com.au",
  "pid": 28,
  "level": 30,
  "logContext": "IlfTuHCPI",
  "repository": "renovate-test/ruby-three",
  "msg": "External host error causing abort - skipping",
  "time": "2023-04-04T10:30:11.664Z",
  "v": 0
}
{
  "name": "renovate",
  "hostname": "ip-10-37-5-195.delivery.realestate.com.au",
  "pid": 28,
  "level": 20,
  "logContext": "IlfTuHCPI",
  "repository": "renovate-test/ruby-three",
  "msg": "Repository result: external-host-error, status: onboarded, enabled: true, onboarded: true",
  "time": "2023-04-04T10:30:11.664Z",
  "v": 0
}
```

**Comment by rarkins** [comment]
Please start a GitHub Discussion in the main Renovate repo as this behavior is nothing specific to the on-prem edition here
