### ISSUE TITLE
Command failed: install-tool python 3.11

### ISSUE THREAD

**Issue by natan-abolafya** [mend/renovate-on-prem#306]
Hi.
In one of our repositories we have this in `renovate.json`
```
  "constraints": {
    "python": "3.11"
  },
```
The repository also utilizes pip-compile in case that's relevant. 
And the PRs fail with this error
![image](https://github.com/mend/renovate-on-prem/assets/64091305/2d4b6462-395f-4934-b67a-0c41c9c4026d)

Renovate docker image: 5.0.0
The relevant debug logs below.
I can't see anything else relevant in the logs. I don't want to drop the whole file as it includes too much detail of our repos. Let me know if I should look for some term.

First `stdout` without the `\n`s.
```
[13:43:52.149] INFO (1168): Installing tool python v3.11...
[13:43:52.154] INFO (1168): Preparing legacy tool python ...
Invalid version: 3.11
[13:43:52.180] FATAL (1168): Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11
    err: {
      \"type\": \"Error\",
      \"message\": \"Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11\",
      \"stack\":
          Error: Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11
              at makeError (/snapshot/dist/containerbase-cli.js:44644:13)
              at handlePromise (/snapshot/dist/containerbase-cli.js:45099:29)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async InstallLegacyToolService.execute (/snapshot/dist/containerbase-cli.js:45358:5)
              at async InstallToolService.execute (/snapshot/dist/containerbase-cli.js:45511:7)
              at async InstallToolShortCommand.execute (/snapshot/dist/containerbase-cli.js:45578:14)
              at async InstallToolShortCommand.validateAndExecute (/snapshot/dist/containerbase-cli.js:1317:26)
              at async _Cli.run (/snapshot/dist/containerbase-cli.js:2430:22)
              at async _Cli.runExit (/snapshot/dist/containerbase-cli.js:2438:28)
              at async main (/snapshot/dist/containerbase-cli.js:45710:3)
      \"shortMessage\": \"Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11\",
      \"command\": \"/usr/local/containerbase/bin/install-tool python 3.11\",
      \"escapedCommand\": \"\\\"/usr/local/containerbase/bin/install-tool\\\" python 3.11\",
      \"exitCode\": 1,
      \"failed\": true,
      \"timedOut\": false,
      \"isCanceled\": false,
      \"killed\": false
    }
[13:43:52.186] INFO (1168): Installed tool python with errors in 38ms.
```

The whole log lines:
```
DEBUG: Executing command (repository=appgate-sdp-int/asc-service-deployment, branch=renovate/all-minor-patch)
       "command": "install-tool python 3.11"
DEBUG: rawExec err (repository=appgate-sdp-int/asc-service-deployment, branch=renovate/all-minor-patch)
       "err": {
         "cmd": "/bin/sh -c install-tool python 3.11",
         "stderr": "",
         "stdout": "[13:43:52.149] INFO (1168): Installing tool python v3.11...\n[13:43:52.154] INFO (1168): Preparing legacy tool python ...\nInvalid version: 3.11\n[13:43:52.180] FATAL (1168): Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11\n    err: {\n      \"type\": \"Error\",\n      \"message\": \"Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11\",\n      \"stack\":\n          Error: Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11\n              at makeError (/snapshot/dist/containerbase-cli.js:44644:13)\n              at handlePromise (/snapshot/dist/containerbase-cli.js:45099:29)\n              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n              at async InstallLegacyToolService.execute (/snapshot/dist/containerbase-cli.js:45358:5)\n              at async InstallToolService.execute (/snapshot/dist/containerbase-cli.js:45511:7)\n              at async InstallToolShortCommand.execute (/snapshot/dist/containerbase-cli.js:45578:14)\n              at async InstallToolShortCommand.validateAndExecute (/snapshot/dist/containerbase-cli.js:1317:26)\n              at async _Cli.run (/snapshot/dist/containerbase-cli.js:2430:22)\n              at async _Cli.runExit (/snapshot/dist/containerbase-cli.js:2438:28)\n              at async main (/snapshot/dist/containerbase-cli.js:45710:3)\n      \"shortMessage\": \"Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11\",\n      \"command\": \"/usr/local/containerbase/bin/install-tool python 3.11\",\n      \"escapedCommand\": \"\\\"/usr/local/containerbase/bin/install-tool\\\" python 3.11\",\n      \"exitCode\": 1,\n      \"failed\": true,\n      \"timedOut\": false,\n      \"isCanceled\": false,\n      \"killed\": false\n    }\n[13:43:52.186] INFO (1168): Installed tool python with errors in 38ms.\n",
         "options": {
           "cwd": "/tmp/renovate/github/appgate-sdp-int/asc-service-deployment",
           "encoding": "utf-8",
           "env": {
             "PIP_CACHE_DIR": "/tmp/renovate/cache/others/pip",
             "HOME": "/home/ubuntu",
             "PATH": "/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/go/bin:/opt/containerbase/tools/python/3.11.4/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "LC_ALL": "C.UTF-8",
             "LANG": "C.UTF-8",
             "CONTAINERBASE_CACHE_DIR": "/tmp/renovate/containerbase"
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 1,
         "name": "ExecError",
         "message": "Command failed: install-tool python 3.11\n",
         "stack": "ExecError: Command failed: install-tool python 3.11\n\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/dist/util/exec/common.js:87:24)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at ChildProcess._handle.onexit (node:internal/child_process:291:12)"
       },
       "durationMs": 373
DEBUG: Failed to pip-compile (repository=appgate-sdp-int/asc-service-deployment, branch=renovate/all-minor-patch)
       "err": {
         "cmd": "/bin/sh -c install-tool python 3.11",
         "stderr": "",
         "stdout": "[13:43:52.149] INFO (1168): Installing tool python v3.11...\n[13:43:52.154] INFO (1168): Preparing legacy tool python ...\nInvalid version: 3.11\n[13:43:52.180] FATAL (1168): Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11\n    err: {\n      \"type\": \"Error\",\n      \"message\": \"Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11\",\n      \"stack\":\n          Error: Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11\n              at makeError (/snapshot/dist/containerbase-cli.js:44644:13)\n              at handlePromise (/snapshot/dist/containerbase-cli.js:45099:29)\n              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n              at async InstallLegacyToolService.execute (/snapshot/dist/containerbase-cli.js:45358:5)\n              at async InstallToolService.execute (/snapshot/dist/containerbase-cli.js:45511:7)\n              at async InstallToolShortCommand.execute (/snapshot/dist/containerbase-cli.js:45578:14)\n              at async InstallToolShortCommand.validateAndExecute (/snapshot/dist/containerbase-cli.js:1317:26)\n              at async _Cli.run (/snapshot/dist/containerbase-cli.js:2430:22)\n              at async _Cli.runExit (/snapshot/dist/containerbase-cli.js:2438:28)\n              at async main (/snapshot/dist/containerbase-cli.js:45710:3)\n      \"shortMessage\": \"Command failed with exit code 1: /usr/local/containerbase/bin/install-tool python 3.11\",\n      \"command\": \"/usr/local/containerbase/bin/install-tool python 3.11\",\n      \"escapedCommand\": \"\\\"/usr/local/containerbase/bin/install-tool\\\" python 3.11\",\n      \"exitCode\": 1,\n      \"failed\": true,\n      \"timedOut\": false,\n      \"isCanceled\": false,\n      \"killed\": false\n    }\n[13:43:52.186] INFO (1168): Installed tool python with errors in 38ms.\n",
         "options": {
           "cwd": "/tmp/renovate/github/appgate-sdp-int/asc-service-deployment",
           "encoding": "utf-8",
           "env": {
             "PIP_CACHE_DIR": "/tmp/renovate/cache/others/pip",
             "HOME": "/home/ubuntu",
             "PATH": "/home/ubuntu/.cargo/bin:/home/ubuntu/.local/bin:/go/bin:/opt/containerbase/tools/python/3.11.4/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "LC_ALL": "C.UTF-8",
             "LANG": "C.UTF-8",
             "CONTAINERBASE_CACHE_DIR": "/tmp/renovate/containerbase"
           },
           "maxBuffer": 10485760,
           "timeout": 900000
         },
         "exitCode": 1,
         "name": "ExecError",
         "message": "Command failed: install-tool python 3.11\n",
         "stack": "ExecError: Command failed: install-tool python 3.11\n\n    at ChildProcess.<anonymous> (/usr/src/app/node_modules/renovate/dist/util/exec/common.js:87:24)\n    at ChildProcess.emit (node:events:525:35)\n    at ChildProcess.emit (node:domain:489:12)\n    at ChildProcess._handle.onexit (node:internal/child_process:291:12)"
       }
```

**Comment by rarkins** [comment]
Where is the value 3.11 coming from?

We generally need debug logs to get an idea what's going on

**Comment by natan-abolafya** [comment]
`3.11` comes from renovate.json file. Using this config https://docs.renovatebot.com/configuration-options/#constraints
```
  "constraints": {
    "python": "3.11"
  },
```

I have the debug logs. The pasted logs aren't enough I guess? Can I send it in private somehow?

**Comment by rarkins** [comment]
Use 3.11.0

**Comment by natan-abolafya** [comment]
that seemed to have done the trick. Thank you.

Do you consider it as a bug or documentation issue since the example is `"python": "3.7"? Or should I just close the issue?

**Comment by rarkins** [comment]
Please create a discussion in the main Renovate repo, we can hopefully support this approach
