### ISSUE TITLE
containerbase version outdated, breaks on go1.21 installs

### ISSUE THREAD

**Issue by sp3nx0r** [mend/renovate-on-prem#307]
Current containerbase version in onprem image is 9.2.0 and [this fix](https://github.com/containerbase/base/commit/803978dca26c3e40134f278cc23f3fddc3bd7353) addresses the change in golang version. Need to bump the containerbase version in the renovate-on-prem image. 

```
ubuntu@mend-renovate-675c5bf789-qxkr8:/usr/src/app$ install-tool golang 1.21.0                                                                                 
[20:39:30.744] DEBUG (3013): discovered distro                                                                                                                        
    distro: {                                                                                                                                                         
      "name": "Ubuntu",                                                                                                                                               
      "versionCode": "focal",                                                                                                                                         
      "versionId": "20.04"                                                                                                                                            
    }                                                                                                                                                                 
[20:39:30.745] DEBUG (3013): prepare commands                                                                                                                         
[20:39:30.747] INFO (3013): Installing tool golang v1.21.0...                                                                                                         
[20:39:30.748] DEBUG (3013): supported tools                                                                                                                          
    tools: [                                                                                                                                                          
      "docker"                                                                                                                                                        
    ]                                                                                                                                                                 
[20:39:30.749] INFO (3013): Preparing legacy tool golang ...                                                                                                          
installing v2 tool golang v1.21.0                                                                                                                                     
curl: (22) The requested URL returned error: 404                                                                                                                      
Download failed: https://dl.google.com/go/go1.21.linux-amd64.tar.gz                                                                                                   
[20:39:30.995] FATAL (3013): Command failed with exit code 1: /usr/local/containerbase/bin/install-tool golang 1.21.0                                                 
    err: {                                                                                                                                                            
      "type": "Error",                                                                                                                                                
      "message": "Command failed with exit code 1: /usr/local/containerbase/bin/install-tool golang 1.21.0",                                                          
      "stack":                                                                                                                                                        
          Error: Command failed with exit code 1: /usr/local/containerbase/bin/install-tool golang 1.21.0                                                             
              at makeError (/snapshot/dist/containerbase-cli.js:44644:13)                                                                                             
              at handlePromise (/snapshot/dist/containerbase-cli.js:45099:29)                                                                                         
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                           
              at async InstallLegacyToolService.execute (/snapshot/dist/containerbase-cli.js:45358:5)                                                                 
              at async InstallToolService.execute (/snapshot/dist/containerbase-cli.js:45511:7)                                                                       
              at async InstallToolShortCommand.execute (/snapshot/dist/containerbase-cli.js:45578:14)                                                                 
              at async InstallToolShortCommand.validateAndExecute (/snapshot/dist/containerbase-cli.js:1317:26)
              at async _Cli.run (/snapshot/dist/containerbase-cli.js:2430:22)
              at async _Cli.runExit (/snapshot/dist/containerbase-cli.js:2438:28)
              at async main (/snapshot/dist/containerbase-cli.js:45710:3)
      "shortMessage": "Command failed with exit code 1: /usr/local/containerbase/bin/install-tool golang 1.21.0",
      "command": "/usr/local/containerbase/bin/install-tool golang 1.21.0",
      "escapedCommand": "\"/usr/local/containerbase/bin/install-tool\" golang 1.21.0",
      "exitCode": 1,
      "failed": true,
      "timedOut": false,
      "isCanceled": false,
      "killed": false
    }
```

**Comment by rarkins** [comment]
Unfortunately this can't be fixed until Monday. In the meantime you might be able to configure constraints for go in renovate config with "<1.21.0" as a workaround, although I'm not able to test it myself

**Comment by rarkins** [comment]
Fixed in https://github.com/mend/renovate-on-prem/releases/tag/5.0.1
